# Generated by Django 4.1 on 2023-01-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='general_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=75, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=75, verbose_name='Last Name')),
                ('other_names', models.CharField(max_length=75, verbose_name='Other Names')),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=75, verbose_name='Gender')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('address', models.CharField(max_length=250, verbose_name='Home Address')),
                ('phone_number', models.IntegerField(verbose_name='Phone Number')),
                ('height', models.IntegerField(verbose_name='Height(cm)')),
                ('weight', models.IntegerField(verbose_name='Weight(kg)')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('O +', 'A+'), ('B+', 'A+'), ('AB+', 'A+'), ('A-', 'A+'), ('O-', 'A+'), ('B-', 'A+'), ('AB-', 'AB-')], max_length=75, verbose_name='Blood_Grop')),
                ('doctor_picture', models.ImageField(blank=True, default='patient_picture/user.png', null=True, upload_to='static/images', verbose_name='Passport')),
                ('staff_id', models.IntegerField(verbose_name='Staff Number')),
                ('d_department', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurosurgery', 'Neurosurgery'), ('ENT', 'ENT'), ('General Surgery', 'General Surgery'), ('Radiology', 'Radiology'), ('Intensive Care', 'Intensive Care'), ('Orthopedic', 'Orthopedic'), ('Gynaecology', 'Gynaecology'), ('Pharmacy', 'Pharmacy'), ('Haematology', 'Haematology'), ('Paediatric', 'Paediatric'), ('Obstetrics', 'Obstetrics')], max_length=75, verbose_name='Department')),
            ],
        ),
    ]
