# Generated by Django 4.1 on 2023-01-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_details',
            name='staff_id',
            field=models.IntegerField(verbose_name='StaffNumber'),
        ),
    ]
